# YAML config file for Kind cluster to specify two nodes
# kind create cluster --config cluster-config.yml --name iweblenscluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
- role: worker


# kind create cluster --config cluster-config.yml --name iweblenscluster
# kubectl apply -f cluster-config.yml

